name: gym_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.16.1 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_screenutil: ^5.5.3+2
  flutter_carousel_slider: ^1.0.9
  sliding_clipped_nav_bar: ^3.1.0+2
  http: ^0.13.4
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  firebase_auth:
  firebase_core:
  cloud_firestore:
  firebase_storage:
  image_picker:

dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/Images/
    - assets/Images/Trainings/1.gif
    - assets/Images/Trainings/10.gif
    - assets/Images/Trainings/11.gif
    - assets/Images/Trainings/12.gif
    - assets/Images/Trainings/13.gif
    - assets/Images/Trainings/2.gif
    - assets/Images/Trainings/3.gif
    - assets/Images/Trainings/4.gif
    - assets/Images/Trainings/5.gif
    - assets/Images/Trainings/6.gif
    - assets/Images/Trainings/7.gif
    - assets/Images/Trainings/8.gif
    - assets/Images/Trainings/9.gif
    - assets/Images/five.PNG
    - assets/Images/four.PNG
    - assets/Images/img.png
    - assets/Images/lo.PNG
    - assets/Images/logo.png
    - assets/Images/one.PNG
    - assets/Images/password.PNG
    - assets/Images/seven.PNG
    - assets/Images/six.PNG
    - assets/Images/three.PNG
    - assets/Images/two.PNG

